### PR TITLE
Fix regression in 4855991

### PR DESCRIPTION
**Pull request by cburmeister**
This commit fixes a regression in 4855991 which is raising an
`AttributeError` on both 2.7.5 and 3.6.5.

```bash
$ pyenv shell 3.6.5; python -c "import email; assert email.header.Header"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'email' has no attribute 'header'
```

### CODE REVIEW

**Comment by moggers87** [comment]
Tests please!

**Comment by moggers87** [comment]
Actually, having had a proper look at this bug I'm not even sure there's regression.

The broken elif statement was added and nothing else in that function was changed, so I suspect that it added during my hunt for the many mystery encoding errors that cropped up while I was porting Salmon to Python 3.

I have two questions:

1. What breaks if you just remove that elif rather than fix it?
2. Do you have an email that Salmon can't process because of this bug? I don't care if you can't share it with me, just that it exists.

**Comment by cburmeister** [comment]
Sorry I just fat fingered the `Close` button...

I'm going to review this further when I get some more free time.

We discovered this when swapping out `lamson` in our project which we use solely for building `MailResponse` objects. In the meantime we've monkey patched `header_from_mime_encoding` to include the changes in this PR which seems to be working.

**Comment by cburmeister** [comment]
@moggers87 any suggestions on how to write a test case for this scenario? 🤔

**Comment by moggers87** [comment]
A simple test that calls `header_from_mime_encoding` with an instance of `email.header.Header` that checks the returned value would be good. The test should live with its friends in https://github.com/moggers87/salmon/blob/master/tests/salmon_tests/encoding_tests.py

**Comment by cburmeister** [comment]
@moggers87 well that's why I'm curious -- there's already [a test that does this](https://github.com/moggers87/salmon/blob/master/tests/salmon_tests/encoding_tests.py#L131) and that line *is* being invoked. 🤔

**Comment by moggers87** [comment]
Right, but we don't fiddle with the imports there to simulate `email.header` being unavailable and we don't actually test that function properly handles `email.header.Header` instances. If we're doing one, we may as well do the other too.

The `with_setup` decorator is your friend: http://nose.readthedocs.io/en/latest/writing_tests.html
